// actions and action creators
export const CHANGE_AUDIO_PLAYING = "changeAudioPlayingState";
export const CHANGE_AUDIO_BUFFERING = "changeAudioBuffering";
export const CHANGE_PLAYER_MODE = "changePlayerMode";
export const CHANGE_CURRENT_PLAYLIST = "changeCurrentPlaylist";
export const CHANGE_CURRENT_ID = "changeCurrentID";
export const UPDATE_MEMORY = "updateMemory";
export const CHANGE_CURRENT_THEME = "changeCurrentTheme";
export const TOGGLE_PLAYER_VISIBILITY = "togglePlayerVisibility";
export const CHANGE_VISITOR_LOCATION = "changeVisitorLocation";